# Generated by Django 4.2.2 on 2023-06-27 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                (
                    "start",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "end",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("allDay", models.BooleanField(default=False)),
            ],
        ),
    ]
