# Generated by Django 4.2.2 on 2023-06-27 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="end",
            field=models.DateTimeField(default=datetime.date.today, verbose_name=()),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start",
            field=models.DateTimeField(default=datetime.date.today, verbose_name=()),
        ),
    ]
